import Link from "next/link";

export const metadata = {
  title: "Investor Pledge â€” Optiloves Invest",
  description: "Our commitment to investors and communities.",
};

export default function Pledge() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-10 space-y-8">
      <header className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">Optiloves Invest â€” Investor Pledge</h1>
        <Link href="/" className="text-sm underline">Back to home</Link>
      </header>

      <p className="text-gray-600">Our Commitment to Investors and Communities</p>

      <div className="grid md:grid-cols-2 gap-8">
        <section className="space-y-4">
          <h2 className="font-semibold">English</h2>
          <p>At Optiloves Invest, our mission is to make real estate investment accessible to all while fighting poverty with love and investment.</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Build Wealth Through Real Estate:</strong> Funds from token sales are used to develop new rental properties in Africa, starting with Kinshasa (Nsele HQ).</li>
            <li><strong>Fair & Transparent Costs:</strong> We retain only 5% for administration and operations (legal, accounting, platform, and property management). 95% goes directly into property development.</li>
            <li><strong>Shared Rental Income:</strong> Rental income generated by these properties is distributed to token holders, proportionally to their investment.</li>
            <li><strong>Mission of Inclusion:</strong> By lowering the entry point to $50 per token, we give ordinary people the chance to invest in real estate, not just the wealthy.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="font-semibold">FranÃ§ais</h2>
          <p>Chez Optiloves Invest, notre mission est de rendre lâ€™investissement immobilier accessible Ã  tous tout en luttant contre la pauvretÃ© par lâ€™amour et lâ€™investissement.</p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>CrÃ©er de la richesse via lâ€™immobilier :</strong> Les fonds issus de la vente de tokens financent de nouveaux biens locatifs en Afrique, Ã  commencer par Kinshasa (siÃ¨ge de Nsele).</li>
            <li><strong>CoÃ»ts justes & transparents :</strong> Nous ne retenons que 5% pour lâ€™administration et les opÃ©rations (juridique, comptabilitÃ©, plateforme et gestion immobiliÃ¨re). 95% vont directement au dÃ©veloppement immobilier.</li>
            <li><strong>Revenus locatifs partagÃ©s :</strong> Les revenus locatifs gÃ©nÃ©rÃ©s sont distribuÃ©s aux dÃ©tenteurs de tokens, proportionnellement Ã  leur investissement.</li>
            <li><strong>Mission dâ€™inclusion :</strong> Avec un ticket dâ€™entrÃ©e Ã  50Â $ par token, nous permettons Ã  tous dâ€™investir, pas seulement aux plus aisÃ©s.</li>
          </ul>
        </section>
      </div>

      <footer className="text-xs text-gray-500">
        Â© 2025 Optiloves Invest â€¢ FIGHTING POVERTY WITH LOVE AND INVESTMENT
      </footer>
    </main>
  );
}
